### ISSUE TITLE
No `close` method on test client

### ISSUE THREAD

**Issue by maoueh** [opscode-cookbooks/database#112]
Trying to update a cookbook to `mysql` cookbook 6.x and `database` 3.x. When calling `mysql_database_user`, I get a `NoMethodError` on `close`.

Code at error is:

```
        def close_test_client
          @test_client.close
        rescue Mysql2::Error
          @test_client = nil
        end
```

I'm not sure right now why `@test_client` is `nil` at this point. Will try to debug this and provide more information and maybe a fix, why not :).

```
NoMethodError: mysql_database_user[git] (gitlab::database_mysql line 44) had an error: NoMethodError: undefined method `close' for nil:NilClass
/tmp/kitchen/cookbooks/database/libraries/provider_database_mysql_user.rb:164:in `close_test_client'
/tmp/kitchen/cookbooks/database/libraries/provider_database_mysql_user.rb:46:in `ensure in block in <class:MysqlUser>'
/tmp/kitchen/cookbooks/database/libraries/provider_database_mysql_user.rb:46:in `block in <class:MysqlUser>'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:315:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/opt/chef/bin/chef-solo:40:in `load'
/opt/chef/bin/chef-solo:40:in `<main>'
```

**Comment by maoueh** [comment]
The problem was that the client was unable to connect to the database. I thought that using `nil` for socket would be ok, but it seems not. Hence, the method `test_client` was failing and then the `ensure` block in the [user present query code](https://github.com/opscode-cookbooks/database/blob/master/libraries/provider_database_mysql_user.rb#L46) was called. 

Since the `@test_client` was nil, instead of reporting the right error saying `Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)`, it was failing with a `NoMethodError`.

I prepared a PR where mysql clients closing are guarded by `nil` test to ensure the method `close` is called only when the instance is set.

**Comment by maoueh** [comment]
FYI, setting `nil` as `:socket` is probably not related to why I was not able to connect to MySQL in the first place, sorry for this false information. The rest of the bug report is still correct however.

**Comment by maoueh** [comment]
And for my connection problem, here the trick. I was specifying the host as `localhost`. It appears that `localhost` [is kind of magic](http://stackoverflow.com/a/5494410) for mysql as it forces socket connection if available. Since with the new `mysql` cookbook, the service is not at the default location anymore, the default socket `/var/lib/mysql/mysql.sock` is not working.

Using `127.0.0.1 instead of `localhost` make it worked correctly.

**Comment by jenssegers** [comment]
I'm getting the same error:

```
================================================================================
Error executing action `create` on resource 'mysql_database_user[gogs]'
================================================================================


NoMethodError
-------------
undefined method `close' for nil:NilClass


Cookbook Trace:
---------------
/root/chef-solo/cookbooks-2/database/libraries/provider_database_mysql_user.rb:164:in `close_test_client'
/root/chef-solo/cookbooks-2/database/libraries/provider_database_mysql_user.rb:46:in `ensure in block in <class:MysqlUser>'
/root/chef-solo/cookbooks-2/database/libraries/provider_database_mysql_user.rb:46:in `block in <class:MysqlUser>'


Resource Declaration:
---------------------
# In /root/chef-solo/cookbooks-3/paas/definitions/database_user.rb

 16: 		mysql_database_user params[:name] do
 17: 			connection  mysql_connection_info
 18: 			password    params[:password]
 19: 			host        params[:host] || "localhost"
 20: 			action      :create
 21: 		end
 22: 

Compiled Resource:
------------------
# Declared in /root/chef-solo/cookbooks-3/paas/definitions/database_user.rb:16:in `block in from_file'

mysql_database_user("gogs") do
  params {:action=>:enable, :password=>"xxx", :name=>"gogs"}
  provider Chef::Provider::Database::MysqlUser
  action [:create]
  retries 0
  retry_delay 2
  username "gogs"
  host "localhost"
  privileges [:all]
  cookbook_name :hosting
  recipe_name "databases"
  connection {:host=>"127.0.0.1", :port=>3306, :username=>"root", :password=>"xxx", :socket=>"/run/mysql-default/mysqld.sock"}
  password "xxx"
end
```

**Comment by jenssegers** [comment]
It seems that I had the 5.6 mysql client installed from dotdeb. I pinned the 5.5 debian package and now it works.
