### ISSUE TITLE
Errors passing Proc to mysql query

### ISSUE THREAD

**Issue by fishnix** [opscode-cookbooks/database#128]
I get this when trying to run this sql script:

```sql
flush privileges;
```

```
================================================================================
           Error executing action `query` on resource 'mysql_database[run script]'
           ================================================================================
           
           TypeError
           ---------
           wrong argument type Proc (expected String)
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb:94:in `query'
           /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb:94:in `block in <class:Mysql>'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/np-jenkins/recipes/slave.rb
           
            32: mysql_database 'run script' do
            33:   connection mysql_connection_info
            34:   sql { ::File.open('/tmp/my_awesome.sql').read }
            35:   action :query
            36: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/np-jenkins/recipes/slave.rb:32:in `from_file'
           
           mysql_database("run script") do
             provider Chef::Provider::Database::Mysql
             action [:query]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             database_name "run script"
             declared_type :mysql_database
             cookbook_name "np-jenkins"
             recipe_name "slave"
             connection {:host=>"127.0.0.1", :username=>"root", :password=>"ilikerandompasswords"}
             sql #<Proc:0x000000063191f0@/tmp/kitchen/cache/cookbooks/np-jenkins/recipes/slave.rb:34>
           end
           
       
       Running handlers:
       [2015-02-06T22:37:27+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-02-06T22:37:27+00:00] ERROR: Exception handlers complete
       [2015-02-06T22:37:27+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 4 resources updated in 35.477210189 seconds
       [2015-02-06T22:37:27+00:00] ERROR: mysql_database[run script] (np-jenkins::slave line 32) had an error: TypeError: wrong argument type Proc (expected String)
       [2015-02-06T22:37:29+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by Sliim** [comment]
Same issue for me.

**Comment by abathur** [comment]
Getting this as well.

**Comment by ajtrichards** [comment]
I'm getting this problem too.

**Comment by philosowaffle** [comment]
I have this problem as well.

**Comment by AutoAutomation** [comment]
I too have this problem...
