### ISSUE TITLE
No resource or method named `mysql2_chef_gem' for `Chef::Recipe "mysql"'

### ISSUE THREAD

**Issue by zanjibar** [opscode-cookbooks/database#130]
database/metadata.rb doesn't have  depends "mysql2_chef_gem" 
so may cause this error ?

```
NoMethodError
-------------
No resource or method named `mysql2_chef_gem' for `Chef::Recipe "mysql"'

Cookbook Trace:
---------------
  /home/ubuntu/chef-solo/cookbooks-2/database/recipes/mysql.rb:2:in `from_file'
  /home/ubuntu/chef-solo/cookbooks-3/jupiter-aws/recipes/test.rb:10:in `from_file'

Relevant File Content:
----------------------
/home/ubuntu/chef-solo/cookbooks-2/database/recipes/mysql.rb:

  1:  # Install the mysql2 gem into Chef's environment
  2>> mysql2_chef_gem 'default' do
  3:    client_version node['mysql']['version'] if node['mysql']
  4:    action :install
  5:  end
  6:  
```

**Comment by multiservicio** [comment]
Same here

```
 NoMethodError
==> default: -------------
==> default: No resource or method named `mysql2_chef_gem' for `Chef::Recipe "mysql"'
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/database/recipes/mysql.rb:2:in `from_file'
==> default:
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/[]/recipes/mysql_server.rb:19:in `from_file'
==> default:
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/[]/recipes/default.rb:41:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef-4/chef-solo-1/cookbooks/database/recipes/mysql.rb:
==> default:
==> default:
==> default:
==> default:   1:  # Install the mysql2 gem into Chef's environment
==> default:
==> default:   2>> mysql2_chef_gem 'default' do
==> default:
==> default:   3:    client_version node['mysql']['version'] if node['mysql']
==> default:
==> default:   4:    action :install
==> default:
==> default:   5:  end
==> default:
==> default:   6:
==> default:

```

**Comment by fishnix** [comment]
You must include the mysql2_chef_gem cookbook - I stumbled on this too, but from the README:

```
MySQL: leverages the mysql2 gem, which can be installed with the mysql2_chef_gem resource prior to use (available on the Supermarket). You must depend on the mysql2_chef_gem cookbook, then use a mysql2_chef_gem resource to install it. The resource allows the user to select MySQL client library versions, as well as optionally select MariaDB libraries.
```

add this to your metadata.rb and you should be good:

```
depends 'mysql2_chef_gem', '~> 1.0.1'
```

**Comment by zanjibar** [comment]
thank you
add   "depends 'mysql2_chef_gem' "  worked fine !
